version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: cimg/node:14.19-browsers
    steps:
      - checkout
      - restore_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: echo "Building for PROD"
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npm run build
          else
            npm -v
          fi
      - persist_to_workspace:
          root: ~/myapp
          paths:
            - build/*
  deploy:
    working_directory: ~/myapp
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - '5d:00:2d:b4:a2:7b:21:1c:61:86:ea:ac:1c:f2:21:db'
      - checkout
      - attach_workspace:
          at: ~/myapp
      - run:
          name: Install gh-pages
          command: |
            npm install -g --silent gh-pages
      - run:
          name: Configure git
          command: |
            git config user.email "circleci@example.com"
            git config user.name "CircleCi"
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --message "[ci skip]" -d build/

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
